apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "10"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"9"},"creationTimestamp":"2020-09-16T01:19:49Z","generation":9,"labels":{"module":"idm"},"name":"idm","namespace":"default","resourceVersion":"2140677","selfLink":"/apis/apps/v1/namespaces/default/deployments/idm","uid":"f3ec9225-6902-4425-b04a-731f23791093"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"component":"idm"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"component":"idm","module":"idm"}},"spec":{"containers":[{"command":["/startidm.sh"],"env":[{"name":"EXTERNAL_NAME","value":"idm-svc"},{"name":"IDM_MOUNT_ROOT","value":"/var/idmdata"},{"name":"JVM_MAX_SIZE","value":"256m"},{"name":"CATALINA_OPTS","value":"-Xmx256m -XX:+UseConcMarkSweepGC"},{"name":"HPSSO_INIT_STRING","value":"abcdefaaaaaaaaas114567890abcdefg$$$$$$ABCDEF"},{"name":"SAML2_ENABLE","value":"true"},{"name":"SAML_KEYSTORE_PASSWORD_KEY","value":"saml_keystore_password_key"},{"name":"saml_keystore_password_key","value":"password"}],"image":"itom-docker.shcartifactory.swinfra.net/hpeswitomsandbox/itom-itsma-idm:1.24.2-b132-190523","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":6,"httpGet":{"path":"/idm-service/api/version-info","port":8080,"scheme":"HTTP"},"initialDelaySeconds":600,"periodSeconds":30,"successThreshold":1,"timeoutSeconds":3},"name":"idm","readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/idm-service/api/version-info","port":8080,"scheme":"HTTP"},"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"resources":{},"securityContext":{"runAsUser":0},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/var/idmdata","name":"nfs","subPath":"idmdata"},{"mountPath":"/var/log/propel/idm","name":"nfs","subPath":"logs/idm"},{"mountPath":"/bin/get_secret","name":"nfs","subPath":"script/get_secret.sh"}]}],"dnsPolicy":"ClusterFirst","initContainers":[{"args":["postgres-svc"],"image":"itom-docker.shcartifactory.swinfra.net/hpeswitomsandbox/itom-itsmax-base-infra-dependency-resolver:4.2.1.0","imagePullPolicy":"IfNotPresent","name":"depends-on","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"nfs","persistentVolumeClaim":{"claimName":"global-volume"}}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2020-10-17T23:00:15Z","lastUpdateTime":"2020-10-17T23:00:15Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2020-10-17T12:27:52Z","lastUpdateTime":"2020-10-18T01:05:03Z","message":"ReplicaSet \"idm-77c5f5466d\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":9,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2020-09-16T01:19:49Z"
  generation: 11
  labels:
    module: idm
  name: idm
  namespace: default
  resourceVersion: "2148635"
  selfLink: /apis/apps/v1/namespaces/default/deployments/idm
  uid: f3ec9225-6902-4425-b04a-731f23791093
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: idm
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: idm
        module: idm
    spec:
      containers:
      - command:
        - /startidm.sh
        env:
        - name: EXTERNAL_NAME
          value: idm-svc
        - name: IDM_MOUNT_ROOT
          value: /var/idmdata
        - name: JVM_MAX_SIZE
          value: 256m
        - name: CATALINA_OPTS
          value: -Xmx256m -XX:+UseConcMarkSweepGC
        - name: HPSSO_INIT_STRING
          value: abcdefaaaaaaaaas114567890abcdefg$$$$$$ABCDEF
        - name: SAML2_ENABLE
          value: "true"
        - name: SAML_KEYSTORE_PASSWORD_KEY
          value: saml_keystore_password_key
        - name: saml_keystore_password_key
          value: password
        image: itom-docker.shcartifactory.swinfra.net/hpeswitomsandbox/itom-itsma-idm:1.24.2-b132-190523
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /idm-service/api/version-info
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 1000
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 3
        name: idm
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /idm-service/api/version-info
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/idmdata
          name: nfs
          subPath: idmdata
        - mountPath: /var/log/propel/idm
          name: nfs
          subPath: logs/idm
        - mountPath: /bin/get_secret
          name: nfs
          subPath: script/get_secret.sh
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - postgres-svc
        image: itom-docker.shcartifactory.swinfra.net/hpeswitomsandbox/itom-itsmax-base-infra-dependency-resolver:4.2.1.0
        imagePullPolicy: IfNotPresent
        name: depends-on
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: global-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-10-17T23:00:15Z"
    lastUpdateTime: "2020-10-17T23:00:15Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-10-17T12:27:52Z"
    lastUpdateTime: "2020-10-18T02:16:44Z"
    message: ReplicaSet "idm-66b4848f95" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 11
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1
